#!/bin/sh
#
# @Author: akliuxingyuan
# @Date: 2020-12-09 15:12:01
# @Description: gnome desktop environment auto poweroff shell script for cron
# 

set -e

export DISPLAY=:0 # modify on depend
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u)/bus
cron_poweroff_logfile=$HOME/poweroff.log


echo -e '\n╰─────────────────────────────────────────╯' >> $cron_poweroff_logfile 2>&1

echo '╭───────────'$(date +"%Y-%m-%d %H:%M:%S")'───────────╮' >> $cron_poweroff_logfile 2>&1

gnome-session-quit --power-off >> $cron_poweroff_logfile 2>&1
