#!/bin/sh

# use awk to filter ip address information

ip a | awk '/^[0-9]+:/{ printf "+"; for(i=1; i<=58; i++){printf "-"} printf "+\n"; printf "|\033[36m%-58s\033[0m|\n" ,$2 }/inet[^6]+/{printf "|%-6s\033[35m%-52s\033[0m|\n", " ",$2}/inet6/{printf "|%-6s\033[34m%-52s\033[0m|\n", " ",$2} END{printf "+"; for(i=1; i<=58; i++){printf "-"} printf "+\n"}'
